####### These are the adaptors #######
###### run as sh submit-cutadapt.sh $inpath $outpath test.fastq

nextera="-b AATGATACGGCGACCACCGAGATCTACAC -b AATGATACGGCGACCACCGAGATCTACACNNNNNNNNTCGTCGGCAGCGTC -b CAAGCAGAAGACGGCATACGAGAT -b CAAGCAGAAGACGGCATACGAGATNNNNNNNNGTCTCGTGGGCTCGG -b AATGATACGGCGACCACCGAGATCTACACGCCTCCCTCGCGCCATCAG -b CAAGCAGAAGACGGCATACGAGATNNNNNNNNCGGTCTGCCTTGCCAGCCCGCTCAG -b AATGATACGGCGACCACCGA -b CAAGCAGAAGACGGCATACGA -b CTGTCTCTTATACACATCTAGATGTGTATAAGAGACAG -b CTGTCTCTTATACACATCT -b AGATGTGTATAAGAGACAG -b ATCGGAAGAGCACACGTCTGAACTCCAGTCAC -b GATCGGAAGAGCGTCGTGTAGGGAAAGAGTGT"
smarter="-b AAGCAGTGGTATCAACGCAGAGTACNNNNN -b AAGCAGTGGTATCAACGCAGAGTAC -b AAGCAGTGGTATCAACGCAGAGT"
illuminase="-b ACACTCTTTCCCTACACGACGCTGTTCCATCT -b CAAGCAGAAGACGGCATACGAGCTCTTCCGATCT -b AATGATACGGCGACCACCGAGATCTACACTCTTTCCCTACACGACGCTCTTCCGATCT -b ACACTCTTTCCCTACACGACGCTCTTCCGATCT"
illuminape="-b CTCGGCATTCCTGCTGAACCGCTCTTCCGATCT -b CAAGCAGAAGACGGCATACGAGATCGGTCTCGGCATTCCTGCTGAACCGCTCTTCCGATCT -b CGGTCTCGGCATTCCTACTGAACCGCTCTTCCGATCT"
illuminamultiplex="-b GATCGGAAGAGCACACGTCT -b AATGATACGGCGACCACCGAGATCTACACTCTTTCCCTACACGACGCTCTTCCGATCT -b GTGACTGGAGTTCAGACGTGTGCTCTTCCGATCT -b GATCGGAAGAGCACACGTCTGAACTCCAGTCAC -b GTGACTGGAGTTCAGACGTGTGCTCTTCCGATCT"
illuminapcr="-b CAAGCAGAAGACGGCATACGAGATCGTGATGTGACTGGAGTTC -b CAAGCAGAAGACGGCATACGAGATACATCGGTGACTGGAGTTC -b CAAGCAGAAGACGGCATACGAGATGCCTAAGTGACTGGAGTTC -b CAAGCAGAAGACGGCATACGAGATTGGTCAGTGACTGGAGTTC -b CAAGCAGAAGACGGCATACGAGATCACTGTGTGACTGGAGTTC -b CAAGCAGAAGACGGCATACGAGATATTGGCGTGACTGGAGTTC -b CAAGCAGAAGACGGCATACGAGATGATCTGGTGACTGGAGTTC -b CAAGCAGAAGACGGCATACGAGATTCAAGTGTGACTGGAGTTC -b CAAGCAGAAGACGGCATACGAGATCTGATCGTGACTGGAGTTC -b CAAGCAGAAGACGGCATACGAGATAAGCTAGTGACTGGAGTTC -b CAAGCAGAAGACGGCATACGAGATGTAGCCGTGACTGGAGTTC -b CAAGCAGAAGACGGCATACGAGATTACAAGGTGACTGGAGTTC"
truseq="-b AATGATACGGCGACCACCGAGATCTACACTCTTTCCCTACACGACGCTCTTCCGATCT -b GATCGGAAGAGCACACGTCTGAACTCCAGTCACATCACGATCTCGTATGCCGTCTTCTGCTTG -b GATCGGAAGAGCACACGTCTGAACTCCAGTCACCGATGTATCTCGTATGCCGTCTTCTGCTTG -b GATCGGAAGAGCACACGTCTGAACTCCAGTCACTTAGGCATCTCGTATGCCGTCTTCTGCTTG -b GATCGGAAGAGCACACGTCTGAACTCCAGTCACTGACCAATCTCGTATGCCGTCTTCTGCTTG -b GATCGGAAGAGCACACGTCTGAACTCCAGTCACACAGTGATCTCGTATGCCGTCTTCTGCTTG -b GATCGGAAGAGCACACGTCTGAACTCCAGTCACGCCAATATCTCGTATGCCGTCTTCTGCTTG -b GATCGGAAGAGCACACGTCTGAACTCCAGTCACCAGATCATCTCGTATGCCGTCTTCTGCTTG -b GATCGGAAGAGCACACGTCTGAACTCCAGTCACACTTGAATCTCGTATGCCGTCTTCTGCTTG -b GATCGGAAGAGCACACGTCTGAACTCCAGTCACGATCAGATCTCGTATGCCGTCTTCTGCTTG -b GATCGGAAGAGCACACGTCTGAACTCCAGTCACTAGCTTATCTCGTATGCCGTCTTCTGCTTG -b GATCGGAAGAGCACACGTCTGAACTCCAGTCACGGCTACATCTCGTATGCCGTCTTCTGCTTG -b GATCGGAAGAGCACACGTCTGAACTCCAGTCACCTTGTAATCTCGTATGCCGTCTTCTGCTTG"
adaptor="$illuminase $illuminape $illuminamultiplex"

inpath=$1
outpath=$2
myfiles="$3"

for myfile in $myfiles
	do
	myfor="$inpath/$myfile"	
	bsub -M 4000000 -R  "rusage[mem=4000]" -q normal -o cutadapt-$myfile.out -e cutadapt-$myfile.err -J cutadapt-$myfile "cutadapt $truseq -m 36 -q 20 $myfor-good.fastq | cutadapt -e 0.05 $adaptor -m 36 -q 20 - | cutadapt $illuminapcr -m 36 -q 20 - | cutadapt $nextera -m 36 -q 20 - | cutadapt $smarter -m 36 -q 20 - > $myfor-cut.fastq"
done
